<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>ASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>%%.*</string>
			<key>name</key>
			<string>comment.line.percentage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric constant</string>
			<key>match</key>
			<string>\b(\-?[0-9]+(\.[0-9]+)?(e[\+\-][0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Label</string>
			<key>match</key>
			<string>\$.+</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(Add|Subtract|Negate|Multiply|Divide|Remainder)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(FAdd|FSubtract|FNegate|FMultiply|FDivide)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(And|Or|Nand|Nor|Xor|BEqual|BNegate)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(BTAnd|BTOr|BTNand|BTNor|BTXor|BTEqual|BTNegate)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(ConvertF|ConvertI)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(Duplicate|Exchange|Pop|PushI|PushD|PushF|PushPC|PopPC|LoadC|LoadI|LoadF|StoreC|StoreI|StoreF|Memtop)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(Label|Jump|JumpFalse|JumpTrue|JumpNeg|JumpPos|JumpFNeg|JumpFPos|JumpFZero|Call|JumpV|CallV|Return|Halt)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(DLabel|DataC|DataI|DataF|DataS|DataZ|DataD|PStack)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(Printf|Nop)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm</string>
	<key>uuid</key>
	<string>8abdcdbc-0c41-4971-b9c0-13b000dcdc9e</string>
</dict>
</plist>
