<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bunting</string>
	</array>
	<key>name</key>
	<string>Bunting</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>//[^/\n]*(/[^/\n]+)*(//|/\n|\n|$)</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Floating constant</string>
			<key>match</key>
			<string>(?&lt;=[^A-Za-z_~0-9])(\-?([0-9]+\.[0-9]+)(e(\+|\-)?[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integer constant</string>
			<key>match</key>
			<string>(?&lt;=[^A-Za-z_~0-9])(\-?[0-9]+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean constant</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Character constant</string>
			<key>match</key>
			<string>'[ -~]</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String constant</string>
			<key>match</key>
			<string>"[^"\n]*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(if|else|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(main|mutate|print|nl|create|copy|length|def|type|call|to|in)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(imm|mut)\b</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>\b(bool|char|int|float|void)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>\+|\-|\*|/|&lt;=|&lt;|==|!=|&gt;=|&gt;|&amp;&amp;|\|\||!|&amp;|:=|:|\$</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bunting</string>
	<key>uuid</key>
	<string>fb986475-22d6-4ed5-bb27-e6a36a004e87</string>
</dict>
</plist>
